core_sources = files(
	'capability.c',
	'capability_call.c',
	'channel.c',
	'cpu/cpu.c',
	'cpu/irq.c',
	'exception.c',
	'id_table.c',
	'message.c',
	'process.c',
	'ring_buffer.c',
	'signal.c',
	'user_return.c',
	'user_upcall.c',
	'sync/condvar.c',
	'sync/mutex.c',
	'sync/rwlock.c',
	'sync/semaphore.c',
	'sync/spinlock.c',
	'threading/kthread.c',
	'threading/sched.c',
	'threading/thread.c',
	'threading/uthread.c',
	'syscall/syscall.c',
	'memory/address_transfer.c',
	'memory/pmm.c',
	'memory/memory_object.c',
	'memory/memory_object_radix.c',
	'memory/vm_space.c',
)
