core_sources = files(
	'cpu/cpu.c',
	'cpu/irq.c',
	'process.c',
	'sync/condvar.c',
	'sync/mutex.c',
	'sync/rwlock.c',
	'sync/semaphore.c',
	'sync/spinlock.c',
	'threading/kthread.c',
	'threading/sched.c',
	'threading/thread.c',
	'threading/uthread.c',
	'syscall/syscall.c',
	'memory/kheap.c',
	'memory/pmm.c',
	'memory/vaddr_alloc.c',
	'memory/vmm.c',
)
