#pragma once

#include <stdint.h>

typedef uint64_t process_id_t;

#define PROCESS_PID_INVALID ((process_id_t)0u)

typedef uintptr_t process_exit_code_t;

enum process_exit_code {
	PROCESS_EXIT_SUCCESS = 0u,

	PROCESS_EXIT_SYSTEM_UNKNOWN = 0x100u,

	PROCESS_EXIT_MEMORY_NOT_PRESENT = 0x200u,
	PROCESS_EXIT_MEMORY_PROTECTION,
	PROCESS_EXIT_MEMORY_INVALID,

	PROCESS_EXIT_ARITHMETIC_DIVIDE_BY_ZERO = 0x300u,
	PROCESS_EXIT_ARITHMETIC_OVERFLOW,
	PROCESS_EXIT_ARITHMETIC_BOUND_RANGE,

	PROCESS_EXIT_INSTRUCTION_ILLEGAL = 0x400u,

	PROCESS_EXIT_PRIVILEGE_GENERAL_PROTECTION = 0x500u,

	PROCESS_EXIT_ALIGNMENT_FAULT = 0x600u,

	PROCESS_EXIT_ACCESS_INSTRUCTION_ABORT = 0x700u,
	PROCESS_EXIT_ACCESS_DATA_ABORT,
	PROCESS_EXIT_ACCESS_ADDRESS_ERROR_FETCH,
	PROCESS_EXIT_ACCESS_ADDRESS_ERROR_MEMORY,

	PROCESS_EXIT_BUS_ERROR = 0x800u,

	PROCESS_EXIT_FLOATING_POINT_ERROR = 0x900u,
	PROCESS_EXIT_FLOATING_POINT_SIMD,
};
