[binaries]
c = 'clang'
c_ld = 'lld'
ar = 'llvm-ar'
strip = 'llvm-strip'
nasm = 'nasm'

[host_machine]
system = 'none'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
needs_exe_wrapper = true
skip_sanity_check = true

[built-in options]
# Compilation
c_args = [
  '-ffreestanding',
  '-fno-builtin',
  '-fno-stack-protector',
  '-fno-pic',
  '-mno-red-zone',
  '-m64',
  '-g3',
  '-O0',
  '-fno-omit-frame-pointer',
  '-fno-optimize-sibling-calls',
  '-fno-inline']

# Linking
c_link_args = ['-nostdlib', '-nodefaultlibs', '-nostartfiles', '-Wl,-m,elf_x86_64', '-Wl,--build-id=none']

default_library = 'static'
buildtype = 'debug'
