[binaries]
c = 'clang'
ar = 'llvm-ar'
strip = 'llvm-strip'
ld = 'ld.bfd'
nasm = 'nasm'

[host_machine]
system = 'none'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
needs_exe_wrapper = true
skip_sanity_check = true

[built-in options]
# Compilation
c_args = ['--target=x86_64-elf', '-ffreestanding', '-fno-stack-protector', '-fno-pic', '-mno-red-zone', '-m64', '-O2']

# Linking
c_link_args = ['--target=x86_64-elf', '-fuse-ld=bfd', '-nostdlib', '-Wl,-m,elf_x86_64', '-Wl,--build-id=none']

default_library = 'static'
buildtype = 'release'
